name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ] # O il nome del tuo branch principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: actions/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.FURBO_USERNAME }}
          password: ${{ secrets.FURBO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # <--- Fondamentale per il Raspberry!
          push: true
          tags: ${{ secrets.FURBO_USERNAME }}/paperless-ai:latest
