name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Version Read&Check ---
      - name: Read and validate version
        id: get_version
        run: |
          if [ ! -f VERSION ]; then
            echo "ERRORE: File VERSION non trovato nella root!"
            exit 1
          fi
          VERSION=$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' VERSION)
          if [ -z "$VERSION" ]; then
            echo "ERRORE: Il file VERSION Ã¨ vuoto!"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"
      # --------------------------------------------

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.FURBO_USERNAME }}
          password: ${{ secrets.FURBO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.FURBO_USERNAME }}/paperless-ai:latest
            ${{ secrets.FURBO_USERNAME }}/paperless-ai:${{ steps.get_version.outputs.VERSION }}